import ReactQueryProvider from '@/providers/ReactQuery'
import ThemeContextProvider from '@/theme/index'
import type { Metadata } from 'next'
// import ThemeContextProvider from "@theme";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <body>
          <ReactQueryProvider>
            {children}
          </ReactQueryProvider>
        </body>
      </ThemeContextProvider>
    </html>
  )
}
